# Generated by Django 4.2.5 on 2023-09-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_coursetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='country',
        ),
        migrations.DeleteModel(
            name='CourseType',
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
