# Generated by Django 4.2.5 on 2023-09-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminside', '0007_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('advantages', models.TextField()),
                ('cost_of_studying', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='country_images/')),
            ],
        ),
    ]
