# Generated by Django 4.2.5 on 2023-09-27 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0009_coursetype_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('duration', models.PositiveIntegerField(help_text='Duration in Years')),
                ('description', models.TextField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.country')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.coursetype')),
            ],
        ),
    ]
