# Generated by Django 4.2.5 on 2023-09-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
