# Generated by Django 4.2.5 on 2023-09-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0012_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
