# Generated by Django 4.2.5 on 2023-10-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0017_savedblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
