# Generated by Django 4.2.5 on 2023-10-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_consultantrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
