# Generated by Django 4.2.5 on 2023-10-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
